import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Roboto_Slab } from "next/font/google";
import Banner from "@/components/Banner/banner";
import NavBar from "@/components/nav/navBar";
import SectionCards from "@/components/Card/SectionCards";
import { getPopularVideos, getVideos } from "@/lib/videos";
import { magic } from "@/lib/magic.client";
export const roboto = Roboto_Slab({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const getServerSideProps = async () => {
  const disneyVideos = await getVideos("disney");
  const travel = await getVideos("Productivity");
  const qubits = await getVideos("QubitScube");
  const popular = await getPopularVideos();

  return { props: { disneyVideos, travel, qubits, popular } };
};

export default function Home({
  disneyVideos,
  travel,
  qubits,
  popular,
}: {
  disneyVideos: [{ imgUrl: string; id?: string }];
  travel: [{ imgUrl: string; id?: string }];
  qubits: [{ imgUrl: string; id?: string }];
  popular: [{ imgUrl: string; id?: string }];
}) {
  console.log({ magic });

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar />
      <Banner
        title='Clifford the red dog'
        subTitle='a very cute dog'
        imgUrl='/static/clifford.webp'
      />
      <div className={styles.sectionWrapper}>
        <SectionCards title='Disney' videos={disneyVideos} size='large' />
        <SectionCards title='Popular' videos={popular} size='small' />

        <SectionCards
          title='Productivity Videos'
          videos={travel}
          size='medium'
        />

        <SectionCards title='QubitScube' videos={qubits} size='small' />
      </div>
    </div>
  );
}
