import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { Roboto_Slab } from "next/font/google";
import Banner from "@/components/Banner/banner";
import NavBar from "@/components/nav/navBar";
import Card from "@/components/Card/Card";
export const roboto = Roboto_Slab({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <NavBar username='jad@flix.com' />
      <Banner
        title='Clifford the red dog'
        subTitle='a very cute dog'
        imgUrl='/static/clifford.webp'
      />

      <Card imgUrl='/static/clifford.webp' size='large' />
      <Card imgUrl='/static/clifford.webp' size='medium' />
      <Card imgUrl='/static/clifford.webp' size='small' />
    </div>
  );
}
